config/routes.rb
Rails.application.routes.draw do
  resources :news
  get 'home/index'
  get 'news/:id', to: 'news#show', as: 'notice'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    @news = News.all
  end

  # GET /news/1 or /news/1.json
  def show
    @news = News.find(params[:id])
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_url(@news), notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_url(@news), notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:header, :body, :link, :shape)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://via.placeholder.com/1770x742" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://via.placeholder.com/1770x742" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://via.placeholder.com/1770x742" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<%= render "news/featured" %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-dark btn-floating m-1" href="#!" role="button">
            <i class="bi bi-facebook"></i>
        </a>

        <!-- Twitter -->
        <a class="btn btn-dark btn-floating m-1" href="#!" role="button">
            <i class="bi bi-twitter"></i>
        </a>

        <!-- Instagram -->
        <a class="btn btn-dark btn-floating m-1" href="#!" role="button">
            <i class="bi bi-instagram"></i>
        </a>

        <!-- Linkedin -->
        <a class="btn btn-dark btn-floating m-1" href="#!" role="button">
            <i class="bi bi-linkedin"></i>
        </a>
    </section>

    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>SUSCRÍBETE A NUESTRO BOLETÍN</strong>
            </p>
          </div>

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example21" class="form-control" />
              <label class="form-label" for="form5Example21">Ingresa tu Email</label>
            </div>
          </div>

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Suscríbete
            </button>
          </div>

        </div>

      </form>
    </section>

    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        Únete de forma gratuita.
      </p>
    </section>

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0" style="padding-bottom:20px;">
          <h5 class="text-uppercase">Nuestra empresa</h5>
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white text-decoration-none">Quiénes Somos</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Misión y Visión</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Responsabilidad Social</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Propiedad Intelectual</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0" style="padding-bottom:20px;">
          <h5 class="text-uppercase">Secciones</h5>
          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white text-decoration-none">Deporte</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Farándula</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Nacional</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Internacional</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Política</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0" style="padding-bottom:20px;">
          <h5 class="text-uppercase">Te Ayudamos</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white text-decoration-none">Trabaja con nosotros</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Preguntas Frecuentes</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Denuncia</a>
            </li>
            <li>
              <a href="#!" class="text-white text-decoration-none">Mapa del sitio</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0" style="padding-bottom:20px;">
          <h5 class="text-uppercase">Contáctanos</h5>
          <p><i class="fas fa-home me-3"></i> Valparaíso, Chile</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@email.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 56 1 2345 6789 </p>
          <p><i class="fas fa-print me-3"></i> + 56 9 1234 5678 </p>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    &copy; 2022 NEWS HAPPY - Todos los derechos reservados.
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->





app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg" style="padding:20px;">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <i class="bi bi-list-task"></i>
        </button>
        <a class="navbar-brand" href="#">
          <img src="..." width="30" height="24" class="d-inline-block align-text-top">
          Happy News
        </a>
        <div class="offcanvas offcanvas-start text-white bg-dark" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarLabel">News Happy</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body text-center"> 
					<ul class="navbar-nav flex-grow-1 pe-3">
						<li class="nav-item">
							<%= link_to "Inicio", home_index_path, class:"nav-link" %>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Quiénes Somos</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Noticias</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Noticias destacadas</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Dato Útil</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Contáctanos</a>
						</li>
					</ul>
					<hr style="color: #0056b2;"/>
					<button type="button" class="btn btn-dark"><i class="bi bi-facebook"></i></button>
					<button type="button" class="btn btn-dark"><i class="bi bi-twitter"></i></button>
					<button type="button" class="btn btn-dark"><i class="bi bi-instagram"></i></button>
					<button type="button" class="btn btn-dark"><i class="bi bi-linkedin"></i></button>
					<hr style="color: #0056b2;"/>
			</div>			
		</div>
		<div>
		  <button type="button" class="btn btn-dark"><i class="bi bi-person-circle"></i></button>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>News Happy</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        
        <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    </head>

    <body>
        <%= render "layouts/navbar" %>
        <div style="padding:20px;">
            <%= yield %>
        </div>
        <%= render "layouts/footer" %>
    </body>
</html>

app/views/news/_card.html.erb
<div class="col">
    <div class="card h-100" onclick="">
        <img src="https://via.placeholder.com/370x307" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
        <div class="card-footer">
            <small class="text-muted">Last updated 3 mins ago</small>
        </div>
    </div>
</div>

app/views/news/_featured.html.erb
<div class="container text-center" style="padding:20px;">
    <h2>Noticias Destacadas</h2>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div id="news">
            <% @news.each do |news| %>
                <%= render news %>
                <p>
                <%= link_to "Volver al inicio", home_index_path %>
                </p>
            <% end %>            
        </div>
    </div>
</div>

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :header, style: "display: block" %>
    <%= form.text_area :header %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_area :link %>
  </div>

  <div>
    <%= form.label :shape, style: "display: block" %>
    <%= form.number_field :shape %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/news/_news.html.erb
<div id="<%= dom_id news %>">
  <p>
    <strong>Header:</strong>
    <%= news.header %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= news.body %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= news.link %>
  </p>

  <p>
    <strong>Shape:</strong>
    <%= news.shape %>
  </p>

</div>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Show this news", @news %> |
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>News</h1>

<div id="news">
  <% @news.each do |news| %>
    <%= render news %>
    <p>
      <%= link_to "Show this news", news %>
    </p>
  <% end %>
</div>

<%= link_to "New news", new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render "form", news: @news %>

<br>

<div>
  <%= link_to "Back to news", news_index_path %>
</div>

app/views/news/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @news %>
<h1>Holaaaaa</h1>
<div>
  <%= link_to "Edit this news", edit_news_path(@news) %> |
  <%= link_to "Back to news", news_index_path %>

  <%= button_to "Destroy this news", @news, method: :delete %>
</div>